name: Angular CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --if-present
      - name: Build Docker image
        run: docker build -t taskflow-angular .

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: taskflow-angular-image
          path: |
            ./Dockerfile
            ./dist/taskflow/browser
