name: CI Build & Push (No Deploy)

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./taskflow
        run: npm ci

      - name: Build Angular by branch
        working-directory: ./taskflow
        run: |
          if [ "${{ github.ref_name }}" = "dev" ]; then npm run build -- --configuration=development; fi
          if [ "${{ github.ref_name }}" = "test" ]; then npm run build -- --configuration=production; fi
          if [ "${{ github.ref_name }}" = "main" ]; then npm run build -- --configuration=production; fi

      - name: Set tag by branch
        id: meta
        run: |
          if [ "${{ github.ref_name }}" = "dev" ]; then echo "TAG=dev-${GITHUB_SHA}" >> $GITHUB_OUTPUT; fi
          if [ "${{ github.ref_name }}" = "test" ]; then echo "TAG=test-${GITHUB_SHA}" >> $GITHUB_OUTPUT; fi
          if [ "${{ github.ref_name }}" = "main" ]; then echo "TAG=prod-${GITHUB_SHA}" >> $GITHUB_OUTPUT; fi
          # ✅ Fallback for any other branch
          if [ -z "${TAG}" ]; then echo "TAG=${{ github.ref_name }}-${GITHUB_SHA}" >> $GITHUB_OUTPUT; fi


      # ✅ Convert repo name to lowercase (fix for GHCR)
      - name: Convert repo name to lowercase
        id: repo
        run: echo "repo_lower=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKENN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t $REGISTRY/${{ steps.repo.outputs.repo_lower }}:${{ steps.meta.outputs.TAG }} ./taskflow .

      - name: Push image
        run: docker push $REGISTRY/${{ steps.repo.outputs.repo_lower }}:${{ steps.meta.outputs.TAG }}

      - name: Also tag latest for main
        if: github.ref_name == 'main'
        run: |
          docker tag $REGISTRY/${{ steps.repo.outputs.repo_lower }}:${{ steps.meta.outputs.TAG }} $REGISTRY/${{ steps.repo.outputs.repo_lower }}:latest
          docker push $REGISTRY/${{ steps.repo.outputs.repo_lower }}:latest
